# Generated by Django 2.2.2 on 2019-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link_of_song', models.URLField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('angry', models.PositiveIntegerField()),
                ('disgust', models.PositiveIntegerField()),
                ('fear', models.PositiveIntegerField()),
                ('happy', models.PositiveIntegerField()),
                ('neutral', models.PositiveIntegerField()),
                ('sad', models.PositiveIntegerField()),
                ('surprise', models.PositiveIntegerField()),
            ],
        ),
    ]
