# Generated by Django 2.2.2 on 2019-06-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
