# Generated by Django 2.2.2 on 2019-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_songs_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='angry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='disgust',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='fear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='happy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='neutral',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='sad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='songs',
            name='surprise',
            field=models.IntegerField(),
        ),
    ]
