# Generated by Django 2.2.2 on 2019-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190614_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='angry',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='disgust',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='fear',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='happy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='neutral',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='sad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='songs',
            name='surprise',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
